version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orquestradorCentral
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - orquestradorCentral
    depends_on:
      - redis
      - postgres

  nginx:
    image: nginx:alpine
    container_name: orquestradorCentral-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - orquestradorCentral
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: orquestradorCentral-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orquestradorCentral

  postgres:
    image: postgres:15-alpine
    container_name: orquestradorCentral-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: orchestrator_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - orquestradorCentral

networks:
  orquestradorCentral:
    driver: bridge

volumes:
  pgdata: